// BrandColors.swift
// Train Today — Apps for Hope
// Developed by Tara Knight | @Hopetheservicedoodle
//
// Canonical brand token reference for the Apps for Hope design system.
// See: Brand Palette Consolidation Plan.docx
//
// All shared tokens below are auto-generated by Xcode from Assets.xcassets
// via GeneratedAssetSymbols.swift. This file documents the canonical token set
// and defines accentInteractive explicitly to guarantee the shared hex value.
//
// ─── Shared canonical tokens (auto-generated from asset catalog) ─────────────
//
//   Color.background         — warm cream, primary app background
//   Color.surface            — white, card and modal surfaces
//   Color.fillSecondary      — light taupe, inactive pills and dividers
//   Color.textPrimary        — dark charcoal, all primary labels
//   Color.textSecondary      — mid-gray, captions and metadata
//   Color.accentInteractive  — #386F3F dark sage, ALL interactive roles (see below)
//   Color.accentLight        — light sage, decorative fills ONLY (never text/icon fg)
//   Color.accentLighter      — lightest sage, decorative opacity overlays only
//   Color.success            — confirmation and completion states
//   Color.warning            — caution states (use as bg fill with textPrimary on top)
//   Color.error              — destructive and error states
//
// ─── TT-specific tokens (auto-generated, not part of shared canonical set) ───
//
//   Color.fillBorder         — warm taupe, card borders and secondary UI structure
//   TTColor.obedience/publicAccess/task/relationship — see AppColors+TT.swift

import SwiftUI

extension Color {

    // MARK: - Shared interactive accent
    // Defined as inline RGB to match the canonical value (#386F3F) across all
    // Apps for Hope apps and prevent accidental hex drift between asset slots.
    // White text on this surface: 5.98:1 (WCAG AA). On cream bg: 5.27:1 (WCAG AA).
    // Do not substitute accentLight, accentLighter, or any category color here.
    static var accentInteractive: Color {
        Color(red: 56/255, green: 111/255, blue: 63/255) // #386F3F
    }
}
